package:
  name: petsc
  version: "3.6.0"

source:
  fn: petsc-lite-3.6.0.tar.gz
  url: http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-3.6.0.tar.gz

build:
  number: 1

requirements:
  build:
    - mpi4py
    - numpy
    - python

  run:
    - mpi4py
    - numpy
    - python

about:
  home: http://www.mcs.anl.gov/petsc/
  license: PETSc
  summary: 'PETSc: Portable, Extensible Toolkit for Scientific Computation'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
