# Builds a Docker image from source using as many
# upstream Ubuntu packages as possible.
# An official build of this Dockerfile is maintained at:
# https://registry.hub.docker.com/u/fenicsproject/stable-src/
# Author:
# Jack S. Hale <jack.hale@uni.lu>

# >> docker build -t fenics27 -f Dockerfile_py27 .

# Add a command to automatically replace all occurrences of the non-utf8 names.
FROM fenics_base:latest
MAINTAINER fenics-project <fenics@fenicsproject.org>

ENV HOME /root

RUN rm /bin/sh && ln -s /bin/bash /bin/sh

CMD ["/sbin/my_init"]


RUN cd /tmp/fenics-recipes && conda build --python 2.7 --python 3.4 --no-test petsc
RUN cd /tmp/fenics-recipes && conda build --python 2.7 --python 3.4 --no-test petsc4py
RUN cd /tmp/fenics-recipes && conda build --python 2.7 --python 3.4 --no-test slepc
RUN cd /tmp/fenics-recipes && conda build --python 2.7 --python 3.4 --no-test instant ufl fiat ffc
RUN cd /tmp/fenics-recipes && conda build --python 2.7 --python 3.4 --no-test dolfin
RUN cd /tmp/fenics-recipes && conda build --python 2.7 --python 3.4 --no-test fenics

RUN conda create -y -n f27 python=2.7 numpy=1.9 && conda create -y -n f34 python=3.4 numpy=1.9
