# First of two Dockerfile to build Anaconda packages for FEniCS.
#
# Build instructions:
#   >> docker build -t fenics_base -f Dockerfile_base .
# 
# Author: Oliver Nagy <olitheolix@gmail.com>
FROM continuumio/anaconda:latest
MAINTAINER Oliver Nagy <olitheolix@gmail.com>


# -------------------------------------------------------------------------
# Setup
# -------------------------------------------------------------------------
ENV HOME /root
CMD ["/bin/bash"]

# Replace the default shell with Bash.
RUN rm /bin/sh && ln -s /bin/bash /bin/sh


# -------------------------------------------------------------------------
# Basic dependencies to create Anaconda packages.
# -------------------------------------------------------------------------
RUN apt-get update && apt-get install -y \
    build-essential \
    gfortran \
    git \
    nano \
    pkg-config \
    wget
RUN conda install -y conda-build anaconda-client


# -------------------------------------------------------------------------
# Clone the FEniCS sources and FEniCS recipes.
# -------------------------------------------------------------------------
WORKDIR /tmp
RUN git clone https://bitbucket.org/fenics-project/ffc.git && \
    git clone https://bitbucket.org/fenics-project/fiat.git && \
    git clone https://bitbucket.org/fenics-project/instant.git && \
    git clone https://bitbucket.org/fenics-project/ufl.git && \
    git clone https://bitbucket.org/fenics-project/dolfin.git

# Add the recipes for the Anaconda packages.
ADD . /tmp/fenics-recipes


# -------------------------------------------------------------------------
# Specify the FEniCS branch to select specific versions (eg "master" or
# "1.6.0"), as well as the version given to the Anaconda packages.
# -------------------------------------------------------------------------
ENV FENICS_BRANCH "master"
ENV FENICS_ANACONDA_PACKAGE_VERSION '"1.7.0dev"'


# -------------------------------------------------------------------------
# Pick the correct FEniCS tag and pre-process the sources to make them
# compatible with Python 3 (ie replace some Unicode characters).
# -------------------------------------------------------------------------

# Check out the specified versions in the Git repos.
RUN cd /tmp/ffc && git checkout $FENICS_BRANCH && \
    cd /tmp/fiat && git checkout $FENICS_BRANCH && \
    cd /tmp/instant && git checkout $FENICS_BRANCH && \
    cd /tmp/ufl && git checkout $FENICS_BRANCH && \
    cd /tmp/dolfin && git checkout $FENICS_BRANCH

# Replace problematic Unicode characters in the FEniCS sources.
RUN grep -rli 'Alnæs' * | xargs -i@ sed -i 's/Alnæs/Alnaes/g' @ && \
    grep -rli 'Vikstrøm' * | xargs -i@ sed -i 's/Vikstrøm/Vikstrom/g' @

# Set the version string in FEniCS recipes.
RUN cd /tmp/fenics-recipes && \
    sed -i -e "s/version:.*/version: $FENICS_ANACONDA_PACKAGE_VERSION/g" ffc/meta.yaml && \
    sed -i -e "s/version:.*/version: $FENICS_ANACONDA_PACKAGE_VERSION/g" fiat/meta.yaml && \
    sed -i -e "s/version:.*/version: $FENICS_ANACONDA_PACKAGE_VERSION/g" instant/meta.yaml && \
    sed -i -e "s/version:.*/version: $FENICS_ANACONDA_PACKAGE_VERSION/g" ufl/meta.yaml && \
    sed -i -e "s/version:.*/version: $FENICS_ANACONDA_PACKAGE_VERSION/g" dolfin/meta.yaml && \
    sed -i -e "s/version:.*/version: $FENICS_ANACONDA_PACKAGE_VERSION/g" fenics/meta.yaml
