# Builds a Docker image from source using as many
# upstream Ubuntu packages as possible.
# An official build of this Dockerfile is maintained at:
# https://registry.hub.docker.com/u/fenicsproject/stable-src/
# Author:
# Jack S. Hale <jack.hale@uni.lu>

# >> docker build -t fenics_base_mkl_py27 -f Dockerfile_base_mkl_py27 .

# Add a command to automatically replace all occurrences of the non-utf8 names.
FROM continuumio/miniconda:latest
MAINTAINER fenics-project <fenics@fenicsproject.org>

ENV HOME /root

CMD ["/sbin/my_init"]

RUN apt-get update
RUN conda update -y conda

# Compiler ecosystem.
RUN apt-get install -y \
    build-essential \
    cmake \
    git \
    pkg-config \
    wget

# Additional dependencies.
RUN apt-get install -y \
    libboost-filesystem-dev \
    libboost-iostreams-dev \
    libboost-timer-dev \
    libcgal-dev \
    petsc-dev

RUN conda install -y \
    cmake \
    conda-build \
    jinja2 \
    numpy \
    ply \
    six \
    sympy

ADD . /tmp/fenics-recipes

# Cleanup to save space
#RUN apt-get clean && \ 
#    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Set the HOME environment variable, otherwise import dolfin crashes
# RUN echo "/root" > /etc/container_environment/HOME

# # Enable X11 forwarding for plotting
# RUN echo "X11Forwarding yes" >> /etc/ssh/sshd_config

# # Set LIBGL_ALWAYS_INDIRECT to suppress libGL warning message.
# RUN echo "y" > /etc/container_environment/LIBGL_ALWAYS_INDIRECT

# # Put environment variables into
# RUN echo "source /usr/local/share/dolfin/dolfin.conf" >> /etc/bash.bashrc
