# First of two Dockerfile to build Anaconda packages for FEniCS.
#
# Build with:
#   >> docker build -t fenics_base -f Dockerfile_base .
# 
# Author: Oliver Nagy <olitheolix@gmail.com>
FROM continuumio/anaconda:latest
MAINTAINER Oliver Nagy <olitheolix@gmail.com>

# Admin.
ENV HOME /root
CMD ["/bin/bash"]

# Replace the default shell with Bash.
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# Install the necessary Ubuntu- and Ancaconda libraries to build packages.
RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    nano \
    pkg-config \
    wget
RUN conda install -y conda-build

# Download the source files and repositories to /tmp
WORKDIR /tmp

# Clone the relevant repos from the FEniCS project.
RUN git clone https://github.com/FEniCS/ffc.git && \
    git clone https://github.com/FEniCS/fiat.git && \
    git clone https://github.com/FEniCS/instant.git && \
    git clone https://github.com/FEniCS/ufl.git && \
    git clone https://github.com/FEniCS/dolfin.git

# Add the recipes from the current directory.
ADD . /tmp/fenics-recipes

# Build auxiliary packages. These are not FEniCS specific but Anaconda
# has either no default (Eigen3) or it is too old (SWIG). Therfore, we
# build our own from the just added set of recipes.
RUN cd /tmp/fenics-recipes && conda build eigen3 swig --python 2.7 --python 3.4 --no-test
