package:
  name: fenics
  version: "1.6.0"

requirements:
  run:
    - dolfin
    - ffc
    - fiat
    - ufl
    - instant

about:
  home: http://www.fenicsproject.org
  summary: 'FEniCS is a collection of free software for automated, efficient solution of differential equations'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
