package:
  name: petsc4py
  version: "3.6.0"

source:
  fn: petsc4py-3.6.0.tar.gz
  url: https://bitbucket.org/petsc/petsc4py/downloads/petsc4py-3.6.0.tar.gz

build:
  number: 1

requirements:
  build:
    - numpy
    - petsc
    - python

  run:
    - petsc
    - python

test:
  imports:
    - petsc4py
    - petsc4py.lib

  requires:
    - numpy

about:
  home: https://bitbucket.org/petsc/petsc4py/
  license: BSD License
  summary: 'PETSc for Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
