package:
  name: slepc
  version: "3.6.0"

source:
  fn: slepc-3.6.0.tar.gz
  url: http://slepc.upv.es/download/distrib/slepc-3.6.0.tar.gz

build:
  number: 1

requirements:
  build:
    - petsc
    - python

  run:
    - petsc
    - python

about:
  home: http://www.grycap.upv.es/slepc/
  license: GNU Library or Lesser General Public License (LGPL)
  summary: 'SLEPc: Scalable Library for Eigenvalue Problem Computations'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
