package:
  name: fiat
  version: "1.6.0"

source:
  path: /tmp/fiat


build:
  number: 1

requirements:
  build:
    - python
    - sympy

  run:
    - numpy
    - python
    - sympy

test:
  imports:
    - FIAT

  requires:
    - nose

about:
  home: http://fenicsproject.org/
  license: The GNU Lesser General Public License, version 3.0
  summary: 'FInite element Automatic Tabulator'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
