package:
  name: ufl
  version: "1.6.0"

source:
  path: /tmp/ufl

build:
  number: 1

requirements:
  build:
    - python

  run:
    - python
    - six

test:
  imports:
    - ufl
    - ufl.algorithms
    - ufl.core
    - ufl.corealg
    - ufl.finiteelement
    - ufl.utils

  commands:
    - ufl-version
    - ufl2py --help

  requires:
    - pytest


about:
  home: http://www.fenicsproject.org
  license: The GNU Lesser General Public License, version 3.0
  summary: 'Unified Form Language'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
