#!/bin/bash

mkdir build
cd build

export LIBRARY_PATH=$PREFIX/lib
export INCLUDE_PATH=$PREFIX/include

export BLAS_DIR=$LIBRARY_PATH
export AMD_DIR=$SP_DIR/petsc
export UMFPACK_DIR=$SP_DIR/petsc

cmake .. \
  -DCMAKE_INSTALL_PREFIX=$PREFIX \
  -DCMAKE_INCLUDE_PATH=$INCLUDE_PATH \
  -DCMAKE_LIBRARY_PATH=$LIBRARY_PATH \
  -DPYTHON_EXECUTABLE=`which python` \
  -DDOLFIN_ENABLE_VTK:BOOL=OFF \
  -DDOLFIN_ENABLE_TRILINOS:BOOL=OFF \
  -DDOLFIN_ENABLE_PASTIX:BOOL=OFF \
  -DDOLFIN_ENABLE_PARMETIS:BOOL=OFF \
  -DDOLFIN_ENABLE_HDF5:BOOL=OFF

make -j4 install
