package:
  name: dolfin
  version: "1.6.0"

source:
#  fn: dolfin-1.6.0.tar.gz
#  url: https://bitbucket.org/fenics-project/dolfin/downloads/dolfin-1.6.0.tar.gz
#  md5: 35cb4baf7ab4152a40fb7310b34d5800
  path: /tmp/dolfin


build:
  number: 1

requirements:
  build:
    - python
    - numpy
    - cmake
    - sphinx
    - libxml2
    - swig >=3.0.3
    - numpy
    - ffc
    - ply
    - boost
    - eigen3
    - petsc
    - petsc4py
    - slepc

  run:
    - python
    - numpy
    - libxml2
    - swig >=3.0.3
    - numpy
    - ffc
    - ufl
    - ply
    - boost
    - eigen3
    - petsc
    - petsc4py
    - slepc

test:
  imports:
    - dolfin

  requires:
    - numpy

about:
  home: http://www.fenicsproject.org
  license: The GNU Lesser General Public License, version 3.0
  summary: 'C++/Python library for solving differential equations'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
